### PR TITLE
Grues

### PR DESCRIPTION
**Pull request by Alex-Markham**
I added all the relevant files for this new mcmc structure learning, set up a docker container, and made a config to test it all. I and now that I'm trying to run the config. I'm running `snakemake --verbose --debug --cores 1 --use-singularity --configfile config/grues_test.json` to try to test it all and getting the following error:

```RuleException:
CalledProcessError in file /home/alex/projects/benchpress/workflow/rules/structure_learning_algorithms/grues/rule.smk, line 13:
Command ' singularity  exec --home '/home/alex/projects/benchpress'  --bind '/home/alex/.local/share/virtualenvs/benchpress-91QzsSuE/lib/python3.10/site-packages':'/mnt/snakemake' /home/alex/projects/benchpress/.snakemake/singularity/cbc08f6650d5c9c24611c9ba0aaf1de0.simg bash -c 'set -euo pipefail;  python /home/alex/projects/benchpress/.snakemake/scripts/tmp7gx0y84y.script.py'' returned non-zero exit status 255.
```

I'm not familiar with docker or snakemake, so I'm not really sure how to address this error. I see that line 13 in rule.smk is the problem, and that's the line that calls `script.py`, which is where I wrote the grues wrapper, but I don't understand from the error message whether there's a problem in my python script or something I've done elsewhere. Any ideas or suggestions?

### CODE REVIEW

**Comment by felixleopoldo** [comment]
Hi Alex, could you paste the Dockerfile content here too?

Running
`snakemake --cores 1 --use-singularity --configfile config/grues_test.json`
gives
`/.singularity.d/actions/exec`

**Comment by felixleopoldo** [comment]
You could also upload the Dockerfile to the module folder

**Comment by felixleopoldo** [comment]
OK. Could you try python:3.11.4-bullseye instead of the alpine one?

**Comment by felixleopoldo** [comment]
Ah also, if you don't change the name of the docker image, it will use the same as before. So I suggest either changing the image name/version, or remove the corresponding singularity image from _benchpress/.snakemake/singularity/_

**Comment by Alex-Markham** [comment]
Alright, switching to bullseye made it work like I expected, so I was then able to see and debug the remaining python errors in my script. Everything seems to be working now and I think I've updated all the required files in the algorithms module and the relevant docs. Let me know if anything else is needed, and thanks for your help (and the amazing package)!!

**Comment by felixleopoldo** [comment]
Nice!! I made some comments. If you like you could also consider providing some example run, config, and output to the docs as is done for [BOSS](https://benchpressdocs.readthedocs.io/en/latest/available_structure_learning_algorithms.html#tetrad-boss) e.g, that can help people starting to use it more easyly. It doesn't necessarily have to be the same plots as for BOSS.

**Comment by felixleopoldo** [comment]
Could you also upload the Dockerfile to the module folder?

**Comment by Alex-Markham** [comment]
Can you point me to where the comments are? 

I added the [Dockerfile](https://github.com/Alex-Markham/benchpress/blob/2386bb59646c5666bb2481839705d32964f364d5/workflow/rules/structure_learning_algorithms/grues/Dockerfile) in the one of the commits yesterday.

And now I'm working on adding an example to the docs

**Comment by felixleopoldo** [comment]
For the docs example it should be in docs.rst like [this](https://github.com/felixleopoldo/benchpress/blob/master/workflow/rules/structure_learning_algorithms/tetrad_boss/docs.rst). Then it will appear in the docs when you build it.

**Comment by felixleopoldo** [comment]
For the graph_types in info.json you can put UDG [here](https://github.com/Alex-Markham/benchpress/blob/0bbde17367e254fb1da6e226e65a5998d46006e1/workflow/rules/structure_learning_algorithms/grues/info.json#L11) and add the link [here](https://github.com/Alex-Markham/benchpress/blob/grues/docs/docs_utils.py).

**Comment by felixleopoldo** [comment]
Another thing,there was a but in the benchmarks module which made it not work properly for fixed data, its is corrected now in dev and master.

**Comment by Alex-Markham** [comment]
Alright, I think I addressed all your comments. Let me know if anything else is needed to finish of the PR. Thanks!

**Pull request merged**
