### PR TITLE
Msc Data Science Thesis - Adding Structure Learning Algorithms to Benchpress

### PR DESCRIPTION
**Pull request by aditya003singh**
Adding structure learning algorithms from the Causal-cmd library was my thesis for MSc Data Science, University of Bristol. The causal discovery algorithms that have been added are as follows- Find Two Factor Clusters Algorithm (FTFC), Find One Factor Clusters Algorithm (FOFC), Fast Adjacency Search Algorithm (FAS), Adjacency Skewness Algorithm (FASK), Lingam and Images Continuous (imgs_cont). The code added has no compilation and syntax errors. All the algorithms except FOFC and FTFC have been successfully executed and generate the expected outputs. FOFC and FTFC fail toward the end of the workflow when the results are combined (rule combine_benchmarks_data) as the ROC_data.csv and joint_benchmarks.csv do not get generated.

### CODE REVIEW

**Comment by felixleopoldo** [comment]
Thank you for your contribution Aditya!
Here are some comments:

- The config/config.json should not be changed, since I refer to it in different places.
- It seems like you didn't add the arguments for the algorithms. Did you encounter any problem with passing the arguments or was it intentional?
- Could you change the prefix causalCMD_ to tetrad_ , as for the other algorithms?

**Comment by aditya003singh** [comment]
Hello Felix,

Thank you for your email and your comments. As for your comments:

   - I will change the config file to the one present in the source code
   - I did not face any problems adding the arguments; it was intended to
   be this way. The arguments passed currently are the required ones to kick
   start the algorithms. As per a discussion with James, my supervisor, the
   first task was to integrate the algorithms with the basic set of parameters
   to check for a successful end to end execution.
   - I will change the prefix to tetrad_

I will make the changes and update you soon. Please let me know if you have
any other feedbacks.

Regards,
Aditya

**Comment by felixleopoldo** [comment]
OK, Sounds reasonable.

**Comment by aditya003singh** [comment]
Hi Felix,

Greetings, hope you had a great weekend.

Apologies for the late response, I was trying to get a follow up with the
University to understand if I could change the code before the results.

You may be aware that the contribution to benchpress I made was the
Dissertation Project for my MSc.  Data Science from the University Of
Bristol under the supervision of Dr. James Cussens. As part of the
submission I was required to provide the git hub link for access of the
code that was done during the project. Any commits after the submission
date could convey the information of me tweaking the code post submission.
To avoid this I have not yet made the changes suggested by you. Please be
informed that as soon as my result is published I will go ahead to make the
changes. Please let me know if this is fine with you.

Kind Regards,
Aditya

**Comment by felixleopoldo** [comment]
Hi Aditya,

It's really great that you added these algorithms. No worries, the comments I had were minor, so I can also fix them myself without any problem.

Thanks again for your contributions, it would be nice to read your thesis.

Felix

**Comment by aditya003singh** [comment]
Hello Felix,

I am more than glad to know that you are pleased with my contributions to
Benchpress. Also a big thanks for taking the time out to make the changes
yourself.
Please let me know if you would be interested in reading my thesis and I
will send over a copy to you.

Thanks again for giving me this opportunity to contribute to the amazing
workflow, Benchpress.

Kind Regards,
Aditya

**Comment by felixleopoldo** [comment]
Hi Aditya,

Great to hear that you seemed to like working with Benchpress. I would be very happy to receive a copy of your thesis.

Best
Felix

**Comment by felixleopoldo** [comment]
Great to hear that. I did not receive the thesis. Maybe it is safer sending it separately directly to my email felix leopoldo rios gmail com.

Best

Felix

**Pull request merged**
